spring:

  datasource:
    url: jdbc:postgresql://89.208.198.194/groupfinder
    username: admin
    password: qwerty1234567890
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate